//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Site_2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_Password
    {
        public string Admin_Id { get; set; }
        public string Admin_Password1 { get; set; }
    }
}
