//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Site_2._0.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TransportEntities : DbContext
    {
        public TransportEntities()
            : base("name=TransportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DeptInfo> DeptInfoes { get; set; }
        public virtual DbSet<Driver_Info> Driver_Info { get; set; }
        public virtual DbSet<Routes_Info> Routes_Info { get; set; }
        public virtual DbSet<Student_Info> Student_Info { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Van_Students> Van_Students { get; set; }
        public virtual DbSet<VanDriver_Info> VanDriver_Info { get; set; }
        public virtual DbSet<Vehicle_Info> Vehicle_Info { get; set; }
        public virtual DbSet<VehicleRoute> VehicleRoutes { get; set; }
        public virtual DbSet<Admin_Password> Admin_Password { get; set; }
    }
}
