//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Site_2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student_Info()
        {
            this.Van_Students = new HashSet<Van_Students>();
        }
    
        public int Std_Id { get; set; }
        public Nullable<int> DeptID { get; set; }
        public string Std_FirstName { get; set; }
        public string Std_Semester { get; set; }
        public string Std_Address { get; set; }
        public string Std_No { get; set; }
        public Nullable<System.DateTime> AdmissionDt { get; set; }
        public string Std_Password { get; set; }
    
        public virtual DeptInfo DeptInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Van_Students> Van_Students { get; set; }
    }
}
