//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Site_2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Van_Students
    {
        public int SV_ID { get; set; }
        public Nullable<int> P_ID { get; set; }
        public int Std_Id { get; set; }
        public bool Active { get; set; }
        public System.DateTime JoiningDT { get; set; }
        public Nullable<System.DateTime> EndingDt { get; set; }
    
        public virtual Student_Info Student_Info { get; set; }
        public virtual VanDriver_Info VanDriver_Info { get; set; }
    }
}
