//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Site_2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleRoute
    {
        public int VR_ID { get; set; }
        public int Van_ID { get; set; }
        public int RouteID { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Routes_Info Routes_Info { get; set; }
        public virtual Vehicle_Info Vehicle_Info { get; set; }
    }
}
