//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Site_2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle_Info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle_Info()
        {
            this.VehicleRoutes = new HashSet<VehicleRoute>();
        }
    
        public int Van_Id { get; set; }
        public string Van_Licence { get; set; }
        public Nullable<int> Capacity { get; set; }
        public Nullable<bool> Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleRoute> VehicleRoutes { get; set; }
    }
}
